docs_dir: 'docs'
site_name: Lucid chain wizard specification
# site_url: http://lucidchain.specs.governify.io
site_url: https://lucidchain.github.io/specs/
repo_url: https://github.com/lucidchain/specs
site_description: Lucid chain wizard specification
site_author: ISA Research Group
copyright: by ISA Research Group
theme: 
  name: mkdocs
  custom_dir: overrides
nav:
- Home: 'index.md'
- Specification: 'Specification.md'
- Constraints: 'Constraints.md'
- 'Theme': 'javascript:void(0);'
extra:
  favicon: favicon.ico

#- About:
#    - 'License': 'license.md'
# to deploy to github: mkdocs gh-deploy -c -b gh-pages -v
extra_css: 
  - 'css/custom.css'
extra_javascript:
  - 'js/custom.js' 
plugins:
  - git-revision-date-localized:
      enable_creation_date: true