docs_dir: '.'
site_name: Lucid chain wizard specification
site_url: http://lucidchain.specs.governify.io
repo_url: https://github.com/lucidchain/specs
site_description: Lucid chain wizard specification
site_author: ISA Research Group
site_favicon: favicon.ico
copyright: by ISA Research Group
theme: cosmo
pages:
- Home: 'index.md'
- Specification: 'Specification.md'
- Constraints: 'Constraints.md'
#- About:
#    - 'License': 'license.md'
# to deploy to github: mkdocs gh-deploy -c -b gh-pages -v
