name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs

      # Paso 4: Construir el sitio con MkDocs
      - name: Build the MkDocs site
        run: mkdocs build

      # Paso 4.5: Crear el archivo CNAME
      # - name: Create CNAME file
      #   run: echo "lucidchain.specs.governify.io" > site/CNAME

      # Paso 5: Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.1.1
        with:
          branch: gh-pages
          folder: site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
